MyWorkshop/Controllers/ThoughtsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using MyWorkshop.Models;
using MyWorkshop.ViewModels;
using MyWorkshop.DAL.Abstract;
using System.Linq.Expressions;

namespace MyWorkshop.Controllers
{
    public class ThoughtsController : Controller
    {
        private IUnitOfWork unitOfWork;
        public ThoughtsController(IUnitOfWork uow)
        {
            unitOfWork = uow;
        }

        int pageSize = 3;

        public ActionResult List(string searchString, string tagName, int page = 1)
        {
            page = page < 1 ? 1 : page;

            IEnumerable<Post> result;
            PagingInfo pagingInfo;
            int totalItems;

            if (!String.IsNullOrEmpty(tagName))
            {

                Tag tag = unitOfWork.PostRepository.GetTagByName(tagName);
                if (tag == null)
                {

                    return new HttpNotFoundResult();

                }
                var temp = unitOfWork.PostRepository.GetPostByTagId(tag.Id);
                totalItems = temp.Count();
                result = temp
                        .Skip((page - 1) * pageSize)
                        .Take(pageSize)
                        .ToList();
            }
            else if (!String.IsNullOrWhiteSpace(searchString))
            {
                Expression<Func<Post, bool>> expression = (Post d) => (d.Description.Contains(searchString) || d.Title.Contains(searchString)) && d.Published;
                result = unitOfWork.PostRepository.GetPosts(expression, null, page, pageSize);
                totalItems = unitOfWork.PostRepository.CountPosts(filter: expression);
            }
            else
            {
                result = unitOfWork.PostRepository.GetPosts(page: page, size: pageSize);
                totalItems = unitOfWork.PostRepository.CountPosts(null);
            }

            foreach (var post in result)
            {
                var content = post.Description;
                int index = content.IndexOf("<p>", content.IndexOf("<p>") + 1);
                if (index != -1)
                {
                    post.Description = content.Substring(0, index);
                }
            }

            pagingInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = totalItems
            };

            PostListViewModel model = new PostListViewModel
            {
                Posts = result,
                PagingInfo = pagingInfo
            };

            ViewBag.searchString = searchString;
            ViewBag.tagName = tagName;

            return View(model);
        }

        // GET: Thoughts/View/5
        public ActionResult View(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = unitOfWork.PostRepository.GetPostById((int)id);
            if (post == null || post.Published == false)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        public ActionResult Archive(int year, int month, int page = 1)
        {
            page = page < 1 ? 1 : page;

            IEnumerable<Post> result;
            PagingInfo pagingInfo;
            int totalItems;

            Expression<Func<Post, bool>> expression = (Post p) => (p.Published && p.PostedOn.Year == year && p.PostedOn.Month == month);
            result = unitOfWork.PostRepository.GetPosts(filter: expression);
            totalItems = unitOfWork.PostRepository.CountPosts(expression);

            foreach (var post in result)
            {
                var content = post.Description;
                int index = content.IndexOf("<p>", content.IndexOf("<p>") + 1);
                if (index != -1)
                {
                    post.Description = content.Substring(0, index);
                }
            }

            pagingInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = totalItems
            };

            PostListViewModel model = new PostListViewModel
            {
                Posts = result,
                PagingInfo = pagingInfo
            };

            ViewBag.IsArchive = true;
            ViewBag.Year = year;
            ViewBag.Month = month;

            return View("List", model);
        }


        [ChildActionOnly]
        public ActionResult Sidebar()
        {
            SidebarComplexModel model = new SidebarComplexModel();

            var tags = unitOfWork.PostRepository.GetTagsCounted();

            if (tags.Count > 0)
            {
                int max = tags.Values.Max();
            }

            ViewBag.TagDictionary = tags;

            var posts = unitOfWork.PostRepository.GetPosts(p => p.Published, null, 1, 4);
            model.Posts = posts;

            var archiveEntry = unitOfWork.PostRepository.GetArchive();
            model.ArchiveEntries = archiveEntry;

            return PartialView("_Sidebar", model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyWorkshop/Views/Thoughts/List.cshtml
@model MyWorkshop.ViewModels.PostListViewModel
@using MyWorkshop.Models
@using MyWorkshop.Helpers

@{
    ViewBag.Title = "List";
    ViewBag.ContainerType = "container ";
}

@section header{
    <header id="thoughts-header">
        <div class="header-content">
            <h1>There is nothing good or bad, but thinking makes it so.</h1>
        </div>
    </header>
}

<div class="row">
    <!-- Blog Entries Column -->
    <div class="col-lg-8 col-md-12">
        
        @foreach (var item in Model.Posts)
        {
            if (@item.Published)
            {
                <!-- Blog Post -->
                <div class="card my-4 no-border box-shadow-bottom-black">
                    <img class="card-img-top" style="width:100%" src="~/Content/Images/Thoughts/@item.ImagePath" alt="Card image cap">
                    <div class="card-block">
                        <h2 class="card-title">@item.Title</h2>
                        @if (item.Tags.Count > 0)
                        {
                            <i class="fa fa-tags" aria-hidden="true"></i>
                            foreach (var tag in item.Tags)
                            {
                                @Html.ActionLink(tag.Name, "List", new { tagName = tag.Name }, new { @class = "tag btn btn-sm btn-info" })
                            }
                        }
                        <p class="card-text">@Html.Raw(@item.Description)</p>
                    </div>
                    <div class="card-footer text-muted">
                        <span>Posted on @item.PostedOn</span>
                        <a href="@Url.Action("View", new { id = item.Id })" class="btn btn-info float-right rounded-0">Read <i class="fa fa-arrow-right"></i></a>
                    </div>
                </div>
            }

        }

        <!-- PAGINATION #2 -->
        <nav aria-label="List results pages">
            <ul class="pagination justify-content-center">

                @if (ViewBag.IsArchive == true)
                {
                    @Html.PageLinks(Model.PagingInfo, x => Url.Action("Archive", new { year = ViewBag.Year, month = ViewBag.Month, page = x }))
                }
                else
                {
                    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, searchString = ViewBag.searchString, tagName = ViewBag.tagName }))
                }


                @*@for (var i = 1; i <= ViewBag.Pages; i++)
            {
                if (ViewBag.CurrentPage == i)
                {
                    <li class="page-item active">
                        @Html.ActionLink(i.ToString(), "List", new { page = i }, new { @class = "page-link" })
                    </li>
                }
                else
                {
                    <li class="page-item">
                        @Html.ActionLink(i.ToString(), "List", new { page = i }, new { @class = "page-link" })
                    </li>
                }
            }*@
            </ul>
        </nav>
    </div>

    @Html.Action("Sidebar")

</div>

MyWorkshop/Views/Thoughts/View.cshtml
@model MyWorkshop.Models.Post

@{
    ViewBag.Title = "View";
    ViewBag.ContainerType = "container ";
}

<header id="view-header" class="box-shadow-bottom-black" style='background-image: url("../../Content/Images/Thoughts/@Model.ImagePath");'>
    <div class="view-header-content">
        <h1>@Model.Title</h1>
    </div>
</header>

<div class="row">
    <!-- Blog Entries Column -->
    <div class="col-lg-8 col-md-12">
        <div class="content-wrapper my-4 bg-white p-4 no-border box-shadow-bottom-black">

            @if (Model.Tags.Count > 0)
            {
                <i class="fa fa-tags" aria-hidden="true"></i>
                foreach (var item in Model.Tags)
                {
                    @Html.ActionLink(item.Name, "List", new { tagName = item.Name }, new { @class = "tag btn btn-sm btn-info" })
                }
            }

            <!-- Blog Post -->
            <p>@Html.Raw(@Model.Description)</p>
            <p class="text-muted" style="font-style: italic">Posted on 11.04.2017 12:18:01</p>
            <p>
                @Html.ActionLink("Back to List", "List")
            </p>
        </div>
    </div>

    <!-- Sidebar Widgets Column -->
    @Html.Action("Sidebar")

</div>

MyWorkshop/Views/Thoughts/_Sidebar.cshtml
@model MyWorkshop.ViewModels.SidebarComplexModel

<!-- Sidebar Widgets Column -->
<div class="col-lg-4 col-md-12">
    <!-- Search Widget -->
    <div class="card my-4 no-border box-shadow-bottom-black">
        @using (Html.BeginForm("List", "Thoughts", FormMethod.Get))
            {
            <h5 class="card-header">Search</h5>
            <div class="card-block">
                <div class="input-group">
                    <input type="text" id="searchString" name="searchString" class="form-control rounded-0" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-secondary rounded-0" type="submit">Go!</button>
                    </span>
                </div>
            </div>
        }
    </div>
    <!-- Tag Widget -->
    <div class="card my-4 no-border box-shadow-bottom-black">
        <h5 class="card-header">Tags</h5>
        <div class="card-block">
            <div class="card-text">
                <ul class="list-inline list-unstyled mb-0">
                    @foreach (var td in ViewBag.TagDictionary)
                    {
                        <li class="list-inline-item">
                            @{
                                string tagName = @td.Key;
                            }
                            @Html.ActionLink(@tagName, "List", new { tagName = td.Key }, new { @class = "sidebar-tag btn btn-sm btn-info m-0" })
                        </li>
                                }
                </ul>
            </div>
        </div>
    </div>
    <!-- Latest post Widget -->
    <div class="card my-4 no-border box-shadow-bottom-black">
        <h5 class="card-header">Latest post</h5>
        <div class="card-block">
            <ul class="list-unstyled">

                @foreach (var post in Model.Posts)
            {
                    <li class="media mb-3">


                        <div class="d-flex mr-3" style="width:100px; height:auto">
                            <a href="/Thoughts/View/@post.Id">
                                <img style="width:100px; height:100px" src="~/Content/Images/Thoughts/@post.ImagePath" />
                            </a>
                        </div>
                        <div class="media-body">
                            <a href="/Thoughts/View/@post.Id">
                                <h6 class="mt-0 mb-1">@post.Title</h6>
                            </a>
                            <span class="text-muted">@post.PostedOn.ToShortDateString()</span>
                        </div>

                    </li>
                }
            </ul>
        </div>
    </div>

    <!-- Archive Widget -->
    <div class="card my-4 no-border box-shadow-bottom-black">
        <h5 class="card-header">Archive</h5>
        <div class="card-block">
            <div class="card-text">
                @foreach (var group in Model.ArchiveEntries.GroupBy(m => m.Year))
                {
                    <ul class="list-unstyled">
                        <li>
                            @group.Key
                            <ul>
                                @foreach (var item in group)
                                {
                                    <li>
                                        @Html.RouteLink(
                                            string.Format("{0} ({1})", item.MonthName, item.Total),
                                            "",
                                            new
                                            {
                                                controller = "Thoughts",
                                                action = "Archive",
                                                year = item.Year,
                                                month = item.Month
                                            })
                                    </li>
                                }
                            </ul>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </div>
</div>