MyWorkshop/Areas/Manage/Controllers/HomeController.cs
using MyWorkshop.DAL.Abstract;
using MyWorkshop.ViewModels;
using System.Web.Mvc;

namespace MyWorkshop.Areas.Manage.Controllers
{
    public class HomeController : Controller
    {
        private IUnitOfWork unitOfWork;
        public HomeController(IUnitOfWork uow)
        {
            unitOfWork = uow;
        }
        
        // GET: Manage/Index
        public ActionResult Index()
        {
            ManageViewModel model = new ManageViewModel();

            // model.Posts = context.Posts.OrderByDescending(p => p.Id).Take(3).ToList();
            model.Posts = unitOfWork.PostRepository.GetPosts(null, null, 1, 3);
            model.Albums = unitOfWork.AlbumRepository.GetAlbums(page: 1, size: 4);

            return View(model);
        }
    }
}

MyWorkshop/Controllers/HomeController.cs
using MyWorkshop.DAL.Abstract;
using MyWorkshop.Models;
using MyWorkshop.ViewModels;
using System.Web.Mvc;

namespace MyWorkshop.Controllers
{
    public class HomeController : Controller
    {
        private IUnitOfWork unitOfWork;
        public HomeController(IUnitOfWork uow)
        {
            unitOfWork = uow;
        }

        // GET: Home
        public ActionResult Index()
        {
            ManageViewModel model = new ManageViewModel();

            model.Posts = unitOfWork.PostRepository.GetPosts((Post p) => p.Published, null, 1, 3);
            model.Albums = unitOfWork.AlbumRepository.GetAlbums((Album a) => a.Published, null, false, 1, 4);

            foreach (var post in model.Posts)
            {
                var content = post.Description;
                int index = content.IndexOf("<p>", content.IndexOf("<p>") + 1);
                if (index != -1)
                {
                    post.Description = content.Substring(0, index);
                }
            }

            return View(model);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyWorkshop/Controllers/PhotosController.cs
using System;
using System.Web.Mvc;
using MyWorkshop.Models;
using MyWorkshop.ViewModels;
using System.Net;
using MyWorkshop.DAL.Abstract;
using System.Text.RegularExpressions;

namespace MyWorkshop.Controllers
{
    public class PhotosController : Controller
    {
        private IUnitOfWork unitOfWork;
        public PhotosController(IUnitOfWork uow)
        {
            unitOfWork = uow;
        }

        string serverMapPath = "~/Content/Images/Photos/";
        private string StorageRoot
        {
            get { return HttpContext.Server.MapPath(serverMapPath); }
        }

        // GET: Photos
        public ActionResult Index()
        {
            var firstDay = DateTime.Today.AddDays(-30);
            AlbumComplexModel model = new AlbumComplexModel();

            model.Albums = unitOfWork.AlbumRepository.GetAlbums(filter:(Album a) => (a.Published && a.CreatedOn >= firstDay), includeProp:true);
            model.ArchiveEntries = unitOfWork.AlbumRepository.GetArchive();

            return View(model);
        }

        public ActionResult Archive(int year, int month)
        {
            AlbumComplexModel model = new AlbumComplexModel();

            model.Albums = unitOfWork.AlbumRepository.GetAlbums(filter:(Album a) => (a.Published && a.CreatedOn.Year == year && a.CreatedOn.Month == month));
            model.ArchiveEntries = unitOfWork.AlbumRepository.GetArchive();

            return View("Index", model);
        }

        // Альбом запрашивается по url slug, но нам действительно нужен только айди который вшит в его начале.
        public ActionResult Album(string urlSlug)
        {
            int id;
            bool result = Int32.TryParse(Regex.Match(urlSlug, @"\d+").Value, out id);

            if (result)
            {
                Album album = unitOfWork.AlbumRepository.GetAlbumById(id);
                if (album == null || album.Published == false)
                {
                    return HttpNotFound();
                }
                return View(album);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyWorkshop/Views/Home/Index.cshtml
@model MyWorkshop.ViewModels.ManageViewModel

@{
    ViewBag.Title = "Index";
    ViewBag.ContainerType = "container-fluid "; // insert to layouy the class for main container
}

@section header{

    <header id="home-header">
        <div class="header-content">
            <h1>Welcome to my den</h1>
            <a href="#">
                <span class="fa-stack fa-lg">
                    <i class="fa fa-circle-o fa-stack-2x text-branded"></i>
                    <i class="fa fa-caret-down fa-stack-1x text-branded"></i>
                </span>
            </a>
        </div>
    </header>

}
<div id="about" class="row p-section">
    <div class="container ">
        <div class="row">
            <div class="col-sm-12 text-center ">
                <h2>About</h2>
                <hr class="hr-small" />
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non lacus libero. In porta tincidunt dui, eget bibendum ligula efficitur sed.
                    Praesent lectus sem, ultrices a gravida vel, semper nec nisl. Sed nunc massa, ultrices vitae luctus eget, pellentesque id dolor.
                    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse eget arcu nibh.
                    Vestibulum ultrices, tellus a pretium pellentesque, quam ligula maximus velit, at hendrerit dui ipsum eget augue.
                </p>
            </div>
        </div>
    </div>
</div>

<div id="latestActivityThoughts" class="row bg-inverse text-white p-section">

    <div class="col-sm-12 text-center">
        <h2>Latest thoughts</h2>
        <hr class="hr-small" />
    </div>



    @foreach (var post in Model.Posts)
            {
        <div class="col-xl-4 col-lg-12 col-md-12 col-sm-12 mb-2">
            <div class="card text-gray-dark no-border">
                <img src="~/Content/Images/Thoughts/@post.ImagePath" class="card-img-top w-100 border-radius-0" />
                <div class="card-block">
                    <h3 class="card-title">@post.Title</h3>
                    <h6 class="card-subtitle mb-2 text-muted"></h6>
                    <p class="card-text">@Html.Raw(post.Description)</p>

                </div>
                <div class="card-footer">
                    <small class="text-muted">@post.PostedOn</small>
                    @Html.RouteLink("Read", "Thoughts/View", new { id = post.Id }, new { @class = "btn btn-warning float-right" })

                </div>
            </div>
        </div>
    }



</div>


<div id="latestActivityPhotos" class="row p-section">

    <div class="col-sm-12 text-center py-5">
        <h2>Latest Albums</h2>
        <hr class="hr-small" />
    </div>

    @foreach (var album in Model.Albums)
    {
        <div class="index-album-preview col-xl-3 col-lg-6 col-md-6 col-sm-12 mx-0 my-2 p-0" style="background-image:url(Content/Images/Photos/@album.PreviewImagePath);">
            <a href="@Url.Action("Album", "Photos", new { urlSlug = album.Slug })">
                <div class="album-overlay">
                    <span class="text">@album.Title</span>
                </div>
            </a>
        </div>
    }

</div>